name: budget_app
description: 簡易記帳工具

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:    # ← 改這個名稱
  android: true
  ios: false
  image_path: "assets/icon.png"